spring.datasource.url=jdbc:mysql://mysql:3306/todo_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## Https config
#server.port=8443
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=123456
#server.port=8443
#server.ssl.key-store=classpath:keystore.jks
#server.ssl.key-store-password=12345678
#server.ssl.key-password=12345678
#server.ssl.key-alias=mykey
#server.ssl.key-store-type=PKCS12


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

todo.message.success = Success
todo.message.fail = Fail

spring.security.oauth2.client.registration.facebook.client-id = 1235564550701436
spring.security.oauth2.client.registration.facebook.client-secret = ea09075985df3f73881bcdeae61c548f
